name: API Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Config Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: |
          npm install
          # npm run start
          npm i -g pm2
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart